### ISSUE TITLE
I think this dosen't works with windows right?

### ISSUE THREAD

**Issue by AshwinRaikar88** [galeone/facectrl#1]
Wanted to test it on my device and seems like after looking at the requirements it's impossible !
(Playerctl installed (pacman -S playerctl on Archlinux))

Also what if the users use earpods instead of headphones the training is gonna be pretty hard !

Keeping footage on for a while also attracts security vulnerabilities !?

Keep coding ;) !!!!

**Comment by galeone** [comment]
Hi @AshwinRaikar88 !

I'm not sure but I guess you're right, Playerctl works only on Linux (maybe also on Mac? I haven't checked).

Oh yes, if the user wears earpods it will be pretty hard, but not impossible! I'm pretty sure all depends on the dataset, if we have enough data the network can learn to spot these small differences.

However, I'm closing this issue since this is not "an issue"

Thank you for this message! :+1:
